---
title: "0_preprocess"
author: "iaradsouza1"
date: "2022-07-26"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```


# Instalar bibliotecas necessárias para o preprocessamento

```{r}
packs <- c("gsignal", "data.table", "tidyverse", "magrittr")
for(i in packs) {
  if(!require(i, character.only = T)) install.packages(i, character.only = TRUE)   
}
```

# Calcular as métricas de biomecânica


```{r}

# Calcular as métricas - DADOS ESTÁTICOS ----------------------------------

library(tidyverse)
library(magrittr)

# Carregar funções a serem utilizadas para o preprocessamento
source("code/calc_cop_area.R")

# Obter dados do Momento 1 ------------------------------------------------

# Caminho dos arquivos do momento 2
path_m1 <- "data/dados_plataforma/Dados da plataforma M1/"

# Lista de arquivos
M1 <- list.files(path_m1, recursive = T)
M1 <- M1[!grepl(".docx", M1)]

# Nomes dos arquivos
fn <- sapply(strsplit(M1, "\\/"), "[[", 3)

# Criar metadado com as informações dos indivíduos para o M1
meta_m1 <- data.frame(
  momento = 1, 
  grupo   = sapply(strsplit(M1, "\\/"), "[[", 1),
  ind     = sapply(strsplit(M1, "\\/"), "[[", 2),
  fn      = fn,
  path    = M1,
  trat    = tolower(sapply(strsplit(fn, "_"), "[[", 3))
)

# Calcular as métricas para cada paciente do momento 1
map_df(1:nrow(meta_m1), ~ {
  
  df_f <- filter_cop(
    file_name = paste0(path_m1, meta_m1$path[.x]),
    probs     = c(0.1, 0.9)
  )
  
  df_a <- calculate_area_cop(df_f)
  
  res <- data.frame(t(df_a), ind = meta_m1$ind[.x], trat = meta_m1$trat[.x])
  res
  
}) -> m1

# Obter dados do Momento 2 ------------------------------------------------

# Caminho dos arquivos do momento 2
path_m2 <- "data/dados_plataforma/Dados da plataforma M2/"

# Lista de arquivos
M2 <- list.files(path_m2, recursive = T)
M2 <- M2[!grepl(".docx", M2)]

# Nomes dos arquivos
fn <- sapply(strsplit(M2, "\\/"), "[[", 3)

# Criar metadado com as informações dos indivíduos para o M2
meta_m2 <- data.frame(
  momento = 2, 
  grupo   = sapply(strsplit(M2, "\\/"), "[[", 1),
  ind     = sapply(strsplit(M2, "\\/"), "[[", 2),
  fn      = fn,
  path    = M2,
  trat    = tolower(sapply(strsplit(fn, "_"), "[[", 3))
)

# # Remover os dados de Primiano Francisco, checar se estão corretos:
# meta_m2 %<>% 
#   dplyr::filter(!(ind == "Primiano Francisco"))

# Calcular as métricas para cada paciente do momento 2
map_df(1:nrow(meta_m2), ~ {
  
  df_f <- filter_cop(
    file_name = paste0(path_m2, meta_m2$path[.x]),
    probs     = c(0.1, 0.9)
  )
  
  df_a <- calculate_area_cop(df_f)
  
  res <- data.frame(t(df_a), ind = meta_m2$ind[.x], trat = meta_m2$trat[.x])
  res
  
}) -> m2

# Criar um id para cara individuo

meta_ind <- bind_rows(meta_m1, meta_m2) %>% 
  select(ind, grupo) %>% 
  distinct() %>% 
  mutate(id = paste0("ind", as.numeric(as.factor(ind))))

m1 <- m1 %>% 
  inner_join(meta_ind, by = c("ind")) %>% 
  select(-ind)

m2 <- m2 %>% 
  inner_join(meta_ind, by = c("ind")) %>% 
  select(-ind)

# Salvar resultados
save(m1, meta_m1, m2, meta_m2, meta_ind, file = "output/biomecanica_processado.RData")
```

